stages:
- stage: Unit
  condition: and(or(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')), ne(variables['Build.SourceBranch'], 'refs/heads/main'), not(startswith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  # Integration Test Jobs
  - template: ../Jobs/unit.yml